dns:
  port: 53
  address: 0.0.0.0
  protocol: udp
  soa:
    primary_nameserver: ns1.example.com
    mail_address: hostmaster.example.com
    refresh: 86400
    retry: 7200
    expire: 604800
    minimum: 180

api:
  port: 8080
  address: 0.0.0.0

redis:
  address: redis:6379
  password: ""
  db: 0
  cache:
    ttl: 0  # Cache TTL in seconds, 0 means cache forever (until explicit purge)

mariadb:
  host: mariadb
  port: 3306
  user: root
  password: 123
  dbname: dns_server

log:
  level: info
  file: ""